### PR TITLE
WIP: Reload Image Store

### PR DESCRIPTION
**Pull request by mike-sul**
- Doc on dockerd building and debugging;
- Quick workaround aimed to do a "hot" reload of the dockerd's image store.

### CODE REVIEW

**Comment by mike-sul** [comment]
This is just one of the possible workarounds aimed to do "hot" Image Store reload after container images are updated by using ostree. I'll think about other approaches while improving/iterating over the end-to-end prototype.

**Comment by doanac** [comment]
i don't understand it well, but the scope of the change is small enough that i'm +1 just on that.

**Comment by ricardosalveti** [comment]
Can you extend the commit message explaining the reasoning behind this change? To remind me why now and also later in the future, in case we decide to go this way.

**Comment by mike-sul** [comment]
> Can you extend the commit message explaining the reasoning behind this change? To remind me why now and also later in the future, in case we decide to go this way.

I've updated the commit message.

Using an ostree repo for container images storing and transferring implies updating of images bypassing of the docker daemon API. If container images are updated by bypassing the docker daemon API (e.g.  `docker pull` or `docker load`) then a running docker daemon doesn't see such updates. The daemon has to be restarted in order to make it reload image updates since by default it reads images' and their layers' data from the image and layer store on a file system to RAM only at the daemon startup.
The given change extends the existing configuration reloading functionality, that is triggered on receiving SIGHUP, with the reloading of images' and layers' data from a filesystem.

**Comment by ricardosalveti** [comment]
Quite a lot of extra commits (from upstream) were added, was this expected?

**Comment by mike-sul** [comment]
> Quite a lot of extra commits (from upstream) were added, was this expected?

No, I must have rebased on an incorrect tag/version yesterday when I was updating my changes, will correct it.

**Pull request closed without merging**
